#
# Copyright The Titan Project Contributors.
#

#
# We run a full build (including lint) on each pull request.
#
name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  buildandtest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.212'
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: Build and test
        run: ./gradlew build
