#
# Copyright The Titan Project Contributors.
#

#
# On creating a new tag, we publish our maven artifacts to the titan maven bucket.
#
name: Release

on: create

jobs:
  publish:
    name: Test and publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.212'
      - name: Build and test
        run: ./gradlew build -Pversion=${GITHUB_REF#refs/tags/}
      - name: Publish jar
        run: >
          ./gradlew publish -PmavenBucket=${{ secrets.MAVEN_BUCKET }} -Pversion=${GITHUB_REF#refs/tags/}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
